// AUTO-GENERATED FILE.
// Source: specs/product-structure/
// Definition: specs/product-structure/resolved-screen.yaml
// Do not edit this file directly.
import { NgModule } from '@angular/core';
import { EffectsModule } from '@ngrx/effects';
import { StoreModule } from '@ngrx/store';

import { ProductStructureEffects } from './product-structure.effects';
import { productStructureReducer } from './product-structure.reducer';
import { productStructureFeatureKey } from './product-structure.state';

@NgModule({
  imports: [
    StoreModule.forFeature(productStructureFeatureKey, productStructureReducer),
    EffectsModule.forFeature([ProductStructureEffects]),
  ],
})
export class ProductStructureStoreModule {}
