// AUTO-GENERATED FILE.
// Source: specs/product-structure/
// Definition: specs/product-structure/resolved-screen.yaml
// Do not edit this file directly.
import { createReducer, on } from '@ngrx/store';

import { ProductStructureActions } from './product-structure.actions';
import {
  initialProductStructureState,
  type ProductStructureState,
} from './product-structure.state';

export const productStructureReducer = createReducer(
  initialProductStructureState,
  on(ProductStructureActions.enterPage, (state, action): ProductStructureState => {
    return {
      ...state,
      // TODO(spec): verify expression "null"
      treeError: null,
      // TODO(spec): verify expression "null"
      detailError: null,
      // TODO(spec): verify expression "null"
      saveError: null,
    };
  }),
  on(ProductStructureActions.searchTree, (state, action): ProductStructureState => {
    return {
      ...state,
      // TODO(spec): verify expression "action.condition"
      searchCondition: action.condition,
    };
  }),
  on(ProductStructureActions.clearSearch, (state, action): ProductStructureState => {
    return {
      ...state,
      // TODO(spec): pending update for "検索条件、選択、詳細を初期化" (state)
    };
  }),
  on(ProductStructureActions.loadTree, (state, action): ProductStructureState => {
    return {
      ...state,
      // TODO(spec): verify expression "true"
      treeLoading: true,
      // TODO(spec): verify expression "null"
      treeError: null,
    };
  }),
  on(ProductStructureActions.loadTreeSuccess, (state, action): ProductStructureState => {
    return {
      ...state,
      // TODO(spec): verify expression "action.nodes"
      treeNodes: action.nodes,
      // TODO(spec): verify expression "false"
      treeLoading: false,
    };
  }),
  on(ProductStructureActions.loadTreeFailure, (state, action): ProductStructureState => {
    return {
      ...state,
      // TODO(spec): verify expression "action.error"
      treeError: action.error,
      // TODO(spec): verify expression "false"
      treeLoading: false,
    };
  }),
  on(ProductStructureActions.selectNode, (state, action): ProductStructureState => {
    return {
      ...state,
      // TODO(spec): pending update for "selectedComponentIdとselectedProductIdを更新" (state)
    };
  }),
  on(ProductStructureActions.loadDetail, (state, action): ProductStructureState => {
    return {
      ...state,
      // TODO(spec): verify expression "true"
      detailLoading: true,
      // TODO(spec): verify expression "null"
      detailError: null,
    };
  }),
  on(ProductStructureActions.loadDetailSuccess, (state, action): ProductStructureState => {
    return {
      ...state,
      // TODO(spec): verify expression "action.detail"
      detail: action.detail,
      // TODO(spec): verify expression "false"
      detailLoading: false,
      // TODO(spec): verify expression "false"
      concurrentUpdate: false,
    };
  }),
  on(ProductStructureActions.loadDetailFailure, (state, action): ProductStructureState => {
    return {
      ...state,
      // TODO(spec): verify expression "action.error"
      detailError: action.error,
      // TODO(spec): verify expression "false"
      detailLoading: false,
    };
  }),
  on(ProductStructureActions.saveProduct, (state, action): ProductStructureState => {
    return {
      ...state,
      // TODO(spec): verify expression "true"
      saving: true,
      // TODO(spec): verify expression "null"
      saveError: null,
      // TODO(spec): verify expression "false"
      concurrentUpdate: false,
      // TODO(spec): pending update for "reselectTargetを設定" (state)
    };
  }),
  on(ProductStructureActions.saveProductSuccess, (state, action): ProductStructureState => {
    return {
      ...state,
      // TODO(spec): verify expression "action.detail"
      detail: action.detail,
      // TODO(spec): verify expression "false"
      saving: false,
      // TODO(spec): verify expression "false"
      concurrentUpdate: false,
    };
  }),
  on(ProductStructureActions.saveProductFailure, (state, action): ProductStructureState => {
    return {
      ...state,
      // TODO(spec): verify expression "action.error"
      saveError: action.error,
      // TODO(spec): verify expression "false"
      saving: false,
    };
  }),
  on(ProductStructureActions.concurrentUpdateDetected, (state, action): ProductStructureState => {
    return {
      ...state,
      // TODO(spec): verify expression "true"
      concurrentUpdate: true,
      // TODO(spec): verify expression "false"
      saving: false,
      // TODO(spec): verify expression "action.error"
      saveError: action.error,
    };
  }),
  on(ProductStructureActions.reloadTreeAfterSave, (state, action): ProductStructureState => {
    return {
      ...state,
      // TODO(spec): verify expression "true"
      treeLoading: true,
      // TODO(spec): verify expression "null"
      treeError: null,
    };
  }),
  on(ProductStructureActions.reloadTreeAfterSaveSuccess, (state, action): ProductStructureState => {
    return {
      ...state,
      // TODO(spec): verify expression "action.nodes"
      treeNodes: action.nodes,
      // TODO(spec): verify expression "false"
      treeLoading: false,
    };
  }),
  on(ProductStructureActions.reloadDetail, (state, action): ProductStructureState => {
    return {
      ...state,
      // TODO(spec): verify expression "true"
      detailLoading: true,
      // TODO(spec): verify expression "null"
      detailError: null,
    };
  }),
  on(ProductStructureActions.reloadDetailSuccess, (state, action): ProductStructureState => {
    return {
      ...state,
      // TODO(spec): pending update for "detail更新、同時更新状態と保存エラーを解除" (state)
    };
  }),
  on(ProductStructureActions.cancelEdit, (state, action): ProductStructureState => {
    return {
      ...state,
      // TODO(spec): verify expression "null"
      saveError: null,
      // TODO(spec): verify expression "false"
      concurrentUpdate: false,
    };
  }),
  on(ProductStructureActions.requestDiscardChanges, (state, action): ProductStructureState => {
    return {
      ...state,
      // TODO(spec): verify expression "action.pending"
      pendingOperation: action.pending,
    };
  }),
  on(ProductStructureActions.confirmDiscardChanges, (state, action): ProductStructureState => {
    return {
      ...state,
      // TODO(spec): verify expression "null"
      pendingOperation: null,
    };
  }),
  on(ProductStructureActions.cancelDiscardChanges, (state, action): ProductStructureState => {
    return {
      ...state,
      // TODO(spec): verify expression "null"
      pendingOperation: null,
    };
  }),
  on(ProductStructureActions.clearPendingOperation, (state, action): ProductStructureState => {
    return {
      ...state,
      // TODO(spec): verify expression "null"
      pendingOperation: null,
    };
  }),
);
