// AUTO-GENERATED FILE.
// Source: specs/product-structure/
// Definition: specs/product-structure/resolved-screen.yaml
// Do not edit this file directly.
import type { ProductSearchCondition } from '../models/product-structure-view.models';
import type { ProductTreeNode } from '../models/product-structure-view.models';
import type { ProductDetail } from '../models/product-structure-view.models';
import type { NodeSelection } from '../models/product-structure-view.models';
import type { PendingOperation } from '../models/product-structure-view.models';
import type { PendingOperationType } from '../models/product-structure-view.models';
import type { ApiError } from '../models/product-structure-common.models';
import type { FieldError } from '../models/product-structure-common.models';

export const productStructureFeatureKey = 'productStructure';

export interface ProductStructureState {
  searchCondition: ProductSearchCondition;
  treeNodes: ProductTreeNode[];
  selectedComponentId: string | null;
  selectedProductId: string | null;
  detail: ProductDetail | null;
  treeLoading: boolean;
  detailLoading: boolean;
  saving: boolean;
  treeError: ApiError | null;
  detailError: ApiError | null;
  saveError: ApiError | null;
  concurrentUpdate: boolean;
  pendingOperation: PendingOperation | null;
  reselectTarget: NodeSelection | null;
}

export const initialProductStructureState: ProductStructureState = {
  searchCondition: { keyword: '', categoryId: null },
  treeNodes: [],
  selectedComponentId: null,
  selectedProductId: null,
  detail: null,
  treeLoading: false,
  detailLoading: false,
  saving: false,
  treeError: null,
  detailError: null,
  saveError: null,
  concurrentUpdate: false,
  pendingOperation: null,
  reselectTarget: null,
};
