// AUTO-GENERATED FILE.
// Source: specs/product-structure/
// Definition: specs/product-structure/resolved-screen.yaml
// Do not edit this file directly.
import { Injectable, inject } from '@angular/core';
import { Actions, createEffect, ofType } from '@ngrx/effects';
import { catchError, map, of, switchMap } from 'rxjs';

import { ProductStructureApiService } from '../services/product-structure-api.service';
import * as productStructureMappers from '../mappers/product-structure.mapper';
import { ProductStructureActions } from './product-structure.actions';

@Injectable()
export class ProductStructureEffects {
  private readonly actions$ = inject(Actions);
  private readonly apiService = inject(ProductStructureApiService);

  readonly loadTree$ = createEffect(() =>
    this.actions$.pipe(
      ofType(ProductStructureActions.loadTree),
      switchMap((action) =>
        this.apiService.loadTree(productStructureMappers.mapSearchToApi(action.condition)).pipe(
          map((response) =>
            ProductStructureActions.loadTreeSuccess({
              nodes: response.nodes.map((item) => productStructureMappers.mapTreeDtoToView(item)),
            }),
          ),
          catchError((error: unknown) =>
            of(
              ProductStructureActions.loadTreeFailure({
                error: productStructureMappers.mapHttpError(error),
              }),
            ),
          ),
        ),
      ),
    ),
  );

  readonly loadDetail$ = createEffect(() =>
    this.actions$.pipe(
      ofType(ProductStructureActions.loadDetail),
      switchMap((action) =>
        this.apiService.loadDetail(action).pipe(
          map((response) =>
            ProductStructureActions.loadDetailSuccess({
              detail: productStructureMappers.mapDetailApiToView(response),
            }),
          ),
          catchError((error: unknown) =>
            of(
              ProductStructureActions.loadDetailFailure({
                error: productStructureMappers.mapHttpError(error),
              }),
            ),
          ),
        ),
      ),
    ),
  );

  readonly saveProduct$ = createEffect(() =>
    this.actions$.pipe(
      ofType(ProductStructureActions.saveProduct),
      switchMap((action) =>
        this.apiService.updateDetail(productStructureMappers.mapSavePayloadToApi(action)).pipe(
          map((response) =>
            ProductStructureActions.saveProductSuccess({
              componentId: action.componentId,
              detail: productStructureMappers.mapDetailApiToView(response),
            }),
          ),
          catchError((error: unknown) =>
            of(
              ProductStructureActions.saveProductFailure({
                error: productStructureMappers.mapHttpError(error),
              }),
            ),
          ),
        ),
      ),
    ),
  );

  readonly reloadTreeAfterSave$ = createEffect(() =>
    this.actions$.pipe(
      ofType(ProductStructureActions.reloadTreeAfterSave),
      switchMap((action) =>
        this.apiService.loadTree(productStructureMappers.mapSearchToApi(action.condition)).pipe(
          map((response) =>
            ProductStructureActions.reloadTreeAfterSaveSuccess({
              nodes: response.nodes.map((item) => productStructureMappers.mapTreeDtoToView(item)),
            }),
          ),
          catchError((error: unknown) =>
            of(
              ProductStructureActions.loadTreeFailure({
                error: productStructureMappers.mapHttpError(error),
              }),
            ),
          ),
        ),
      ),
    ),
  );

  readonly reloadDetail$ = createEffect(() =>
    this.actions$.pipe(
      ofType(ProductStructureActions.reloadDetail),
      switchMap((action) =>
        this.apiService.loadDetail(action).pipe(
          map((response) =>
            ProductStructureActions.reloadDetailSuccess({
              detail: productStructureMappers.mapDetailApiToView(response),
            }),
          ),
          catchError((error: unknown) =>
            of(
              ProductStructureActions.loadDetailFailure({
                error: productStructureMappers.mapHttpError(error),
              }),
            ),
          ),
        ),
      ),
    ),
  );
}
