// AUTO-GENERATED FILE.
// Source: specs/product-structure/
// Definition: specs/product-structure/resolved-screen.yaml
// Do not edit this file directly.
import { createActionGroup, emptyProps, props } from '@ngrx/store';

import type { ApiErrorPayload } from '../models/product-structure-payload.models';
import type { LoadDetailPayload } from '../models/product-structure-payload.models';
import type { LoadDetailSuccessPayload } from '../models/product-structure-payload.models';
import type { LoadTreePayload } from '../models/product-structure-payload.models';
import type { LoadTreeSuccessPayload } from '../models/product-structure-payload.models';
import type { ReloadDetailPayload } from '../models/product-structure-payload.models';
import type { ReloadTreeAfterSavePayload } from '../models/product-structure-payload.models';
import type { SaveProductPayload } from '../models/product-structure-payload.models';
import type { SaveProductSuccessPayload } from '../models/product-structure-payload.models';
import type { SearchTreePayload } from '../models/product-structure-payload.models';
import type { SelectNodePayload } from '../models/product-structure-payload.models';
import type { SetPendingOperationPayload } from '../models/product-structure-payload.models';

export const ProductStructureActions = createActionGroup({
  source: 'ProductStructure',
  events: {
    'Enter Page': emptyProps(),
    'Search Tree': props<SearchTreePayload>(),
    'Clear Search': emptyProps(),
    'Load Tree': props<LoadTreePayload>(),
    'Load Tree Success': props<LoadTreeSuccessPayload>(),
    'Load Tree Failure': props<ApiErrorPayload>(),
    'Select Node': props<SelectNodePayload>(),
    'Load Detail': props<LoadDetailPayload>(),
    'Load Detail Success': props<LoadDetailSuccessPayload>(),
    'Load Detail Failure': props<ApiErrorPayload>(),
    'Save Product': props<SaveProductPayload>(),
    'Save Product Success': props<SaveProductSuccessPayload>(),
    'Save Product Failure': props<ApiErrorPayload>(),
    'Concurrent Update Detected': props<ApiErrorPayload>(),
    'Reload Tree After Save': props<ReloadTreeAfterSavePayload>(),
    'Reload Tree After Save Success': props<LoadTreeSuccessPayload>(),
    'Reload Detail': props<ReloadDetailPayload>(),
    'Reload Detail Success': props<LoadDetailSuccessPayload>(),
    'Cancel Edit': emptyProps(),
    'Request Discard Changes': props<SetPendingOperationPayload>(),
    'Confirm Discard Changes': emptyProps(),
    'Cancel Discard Changes': emptyProps(),
    'Clear Pending Operation': emptyProps(),
  },
});
