// AUTO-GENERATED FILE.
// Source: specs/product-structure/
// Definition: specs/product-structure/resolved-screen.yaml
// Do not edit this file directly.
import { createFeatureSelector, createSelector } from '@ngrx/store';

import { productStructureFeatureKey, type ProductStructureState } from './product-structure.state';
import type { ProductStructureViewModel } from '../models/product-structure-view-model';

export const selectProductStructureState = createFeatureSelector<ProductStructureState>(
  productStructureFeatureKey,
);

export const selectSearchCondition = createSelector(
  selectProductStructureState,
  (state) => state.searchCondition,
);
export const selectTreeNodes = createSelector(
  selectProductStructureState,
  (state) => state.treeNodes,
);
export const selectSelectedComponentId = createSelector(
  selectProductStructureState,
  (state) => state.selectedComponentId,
);
export const selectSelectedProductId = createSelector(
  selectProductStructureState,
  (state) => state.selectedProductId,
);
export const selectDetail = createSelector(selectProductStructureState, (state) => state.detail);
export const selectTreeLoading = createSelector(
  selectProductStructureState,
  (state) => state.treeLoading,
);
export const selectDetailLoading = createSelector(
  selectProductStructureState,
  (state) => state.detailLoading,
);
export const selectSaving = createSelector(selectProductStructureState, (state) => state.saving);
export const selectTreeError = createSelector(
  selectProductStructureState,
  (state) => state.treeError,
);
export const selectDetailError = createSelector(
  selectProductStructureState,
  (state) => state.detailError,
);
export const selectSaveError = createSelector(
  selectProductStructureState,
  (state) => state.saveError,
);
export const selectConcurrentUpdate = createSelector(
  selectProductStructureState,
  (state) => state.concurrentUpdate,
);
export const selectPendingOperation = createSelector(
  selectProductStructureState,
  (state) => state.pendingOperation,
);
export const selectReselectTarget = createSelector(
  selectProductStructureState,
  (state) => state.reselectTarget,
);

export const selectProductStructureViewModel = createSelector(
  selectProductStructureState,
  (state): ProductStructureViewModel => state,
);
