// AUTO-GENERATED FILE.
// Source: specs/product-structure/
// Definition: specs/product-structure/resolved-screen.yaml
// Do not edit this file directly.
import { ChangeDetectionStrategy, Component, EventEmitter, Input, Output } from '@angular/core';

import type { ApiError } from '../../models/product-structure-common.models';
import type { NodeSelection } from '../../models/product-structure-view.models';
import type { ProductTreeNode } from '../../models/product-structure-view.models';

@Component({
  selector: 'app-product-tree',
  standalone: false,
  templateUrl: './product-tree.component.html',
  styleUrl: './product-tree.component.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ProductTreeComponent {
  @Input({ required: true })
  nodes!: ProductTreeNode[];

  @Input({ required: true })
  selectedComponentId!: string;

  @Input({ required: true })
  loading!: boolean;

  @Input({ required: true })
  disabled!: boolean;

  @Input({ required: true })
  error!: ApiError;

  @Output()
  readonly nodeSelected = new EventEmitter<NodeSelection>();

  @Output()
  readonly nodeToggled = new EventEmitter<string>();

  expandedNodeIds: Set<string> = new Set<string>();
  focusedNodeId: string | null = null;
}
