// AUTO-GENERATED FILE.
// Source: specs/product-structure/
// Definition: specs/product-structure/resolved-screen.yaml
// Do not edit this file directly.
import {
  ChangeDetectionStrategy,
  Component,
  EventEmitter,
  Input,
  Output,
  OnChanges,
  SimpleChanges,
} from '@angular/core';
import { FormGroup } from '@angular/forms';

import type { ProductSearchCondition } from '../../models/product-structure-view.models';
import {
  createProductSearchForm,
  type ProductSearchForm,
} from '../../forms/product-search-form.factory';

@Component({
  selector: 'app-product-search',
  standalone: false,
  templateUrl: './product-search.component.html',
  styleUrl: './product-search.component.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ProductSearchComponent implements OnChanges {
  @Input({ required: true })
  condition!: ProductSearchCondition;

  @Input({ required: true })
  disabled!: boolean;

  @Output()
  readonly searchRequested = new EventEmitter<ProductSearchCondition>();

  @Output()
  readonly clearRequested = new EventEmitter<void>();

  form!: FormGroup<ProductSearchForm>;

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['condition'] && this.condition) {
      this.form = createProductSearchForm(this.condition);
    }
  }

  emitSearch(): void {
    this.searchRequested.emit(this.form.getRawValue());
  }
}
