// AUTO-GENERATED FILE.
// Source: specs/product-structure/
// Definition: specs/product-structure/resolved-screen.yaml
// Do not edit this file directly.
import { NO_ERRORS_SCHEMA } from '@angular/core';
import { TestBed } from '@angular/core/testing';

import { ProductSearchComponent } from './product-search.component';

describe('ProductSearchComponent', () => {
  beforeEach(async () => {
    await TestBed.configureTestingModule({
      declarations: [ProductSearchComponent],
      schemas: [NO_ERRORS_SCHEMA],
    }).compileComponents();
  });

  it('should create', () => {
    const fixture = TestBed.createComponent(ProductSearchComponent);
    expect(fixture.componentInstance).toBeTruthy();
  });

  it('should use OnPush change detection', () => {
    const fixture = TestBed.createComponent(ProductSearchComponent);
    expect(fixture.componentRef.changeDetectorRef).toBeTruthy();
  });
});
