// AUTO-GENERATED FILE.
// Source: specs/product-structure/
// Definition: specs/product-structure/resolved-screen.yaml
// Do not edit this file directly.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { ReactiveFormsModule } from '@angular/forms';

import { ProductStructureRoutingModule } from './product-structure-routing.module';
import { ProductStructureStoreModule } from './store/product-structure-store.module';
import { ProductStructurePageComponent } from './pages/product-structure-page/product-structure-page.component';
import { ProductSearchComponent } from './components/product-search/product-search.component';
import { ProductTreeComponent } from './components/product-tree/product-tree.component';
import { ProductTreeNodeComponent } from './components/product-tree-node/product-tree-node.component';
import { ProductDetailFormComponent } from './components/product-detail-form/product-detail-form.component';
import { ConcurrentUpdateMessageComponent } from './components/concurrent-update-message/concurrent-update-message.component';
import { UnsavedChangesDialogComponent } from './components/unsaved-changes-dialog/unsaved-changes-dialog.component';

@NgModule({
  declarations: [
    ProductStructurePageComponent,
    ProductSearchComponent,
    ProductTreeComponent,
    ProductTreeNodeComponent,
    ProductDetailFormComponent,
    ConcurrentUpdateMessageComponent,
    UnsavedChangesDialogComponent,
  ],
  imports: [
    CommonModule,
    ReactiveFormsModule,
    ProductStructureRoutingModule,
    ProductStructureStoreModule,
  ],
})
export class ProductStructureModule {}
