// AUTO-GENERATED FILE.
// Source: specs/product-structure/
// Definition: specs/product-structure/resolved-screen.yaml
// Do not edit this file directly.
import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';

import { productStructureAccessGuard } from './guards/product-structure-access.guard';
import { productStructureDeactivateGuard } from './guards/product-structure-deactivate.guard';
import { ProductStructurePageComponent } from './pages/product-structure-page/product-structure-page.component';

const routes: Routes = [
  {
    path: '',
    component: ProductStructurePageComponent,
    canActivate: [productStructureAccessGuard],
    canDeactivate: [productStructureDeactivateGuard],
  },
];

@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule],
})
export class ProductStructureRoutingModule {}
