// AUTO-GENERATED FILE.
// Source: specs/product-structure.md
// Definition: screens/product-structure.yaml
// Do not edit this file directly.

/** View/store model. Shape used by the Store and the UI. */
export interface PendingOperation {
  /** 保留中の操作ID */
  operationId: string;
  /** 保留中の操作ペイロード */
  payload?: string | null;
}
