// AUTO-GENERATED FILE.
// Source: specs/product-structure.md
// Definition: screens/product-structure.yaml
// Do not edit this file directly.

/** View/store model. Shape used by the Store and the UI. */
export interface ProductTreeNode {
  /** 製品ID */
  productId: string;
  /** 製品名 */
  productName: string;
  /** 製品コード */
  productCode: string;
  /** 親製品ID */
  parentId: string | null;
  /** 子ノード */
  children: ProductTreeNode[];
}
