// AUTO-GENERATED FILE.
// Source: specs/product-structure.md
// Definition: screens/product-structure.yaml
// Do not edit this file directly.
import {
  ChangeDetectionStrategy,
  Component,
  type OnDestroy,
  type OnInit,
  inject,
} from '@angular/core';
import { FormBuilder, type FormGroup, Validators } from '@angular/forms';
import { Store } from '@ngrx/store';
import { type Observable, Subject } from 'rxjs';
import { takeUntil } from 'rxjs/operators';

import { ConfirmationService } from '../../../../core/services/confirmation.service';
import type { LoadTreePayload } from '../../models/actions';
import type { ProductDetail, ProductTreeNode } from '../../models/store';
import * as ProductStructureActions from '../../store/product-structure.actions';
import {
  selectCanUpdate,
  selectDetail,
  selectViewModel,
} from '../../store/product-structure.selectors';

@Component({
  selector: 'app-product-structure',
  standalone: false,
  templateUrl: './product-structure.component.html',
  styleUrls: ['./product-structure.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ProductStructureComponent implements OnInit, OnDestroy {
  private readonly fb = inject(FormBuilder);
  private readonly store = inject(Store);
  private readonly confirmation = inject(ConfirmationService);

  readonly vm$ = this.store.select(selectViewModel);
  readonly confirmMessage = '編集内容が保存されていません。変更を破棄してよろしいですか？';
  readonly concurrentMessage =
    '他の利用者によって製品情報が更新されています。最新情報を再取得してください。';

  form!: FormGroup;
  searchForm!: FormGroup;

  readonly expandedNodeIds = new Set<string>();

  private readonly destroy$ = new Subject<void>();
  private currentDetail: ProductDetail | null = null;

  ngOnInit(): void {
    this.form = this.fb.group({
      productName: [{ value: '', disabled: false }, [Validators.required]],
      productCode: [{ value: '', disabled: true }, [Validators.required]],
      price: [{ value: 0, disabled: false }, [Validators.required, Validators.min(0)]],
      description: [{ value: null, disabled: false }],
      revision: [{ value: 0, disabled: true }, [Validators.required]],
    });

    this.searchForm = this.fb.group({
      keyword: [''],
      categoryId: [''],
    });

    this.store
      .select(selectDetail)
      .pipe(takeUntil(this.destroy$))
      .subscribe((detail) => {
        this.currentDetail = detail;
        this.form.reset(detail ? this.detailToFormValue(detail) : this.emptyFormValue());
        this.form.markAsPristine();
      });

    this.store
      .select(selectCanUpdate)
      .pipe(takeUntil(this.destroy$))
      .subscribe((canUpdate) => this.applyEditPermission(canUpdate));

    // Operation: enterPage
    this.store.dispatch(ProductStructureActions.enterPage());
    this.store.dispatch(ProductStructureActions.loadTree(this.buildTreePayload()));
  }

  ngOnDestroy(): void {
    this.destroy$.next();
    this.destroy$.complete();
  }

  // Operation: search
  onSearch(): void {
    this.guardDirty(() =>
      this.store.dispatch(ProductStructureActions.loadTree(this.buildTreePayload())),
    );
  }

  // Operation: clear
  onClear(): void {
    this.guardDirty(() => {
      this.searchForm.reset(this.emptySearchValue());
      this.store.dispatch(ProductStructureActions.clearSearch());
      this.store.dispatch(ProductStructureActions.loadTree(this.buildTreePayload()));
    });
  }

  // Operation: selectNode
  onSelectNode(node: ProductTreeNode): void {
    this.guardDirty(() => {
      this.store.dispatch(ProductStructureActions.selectNode({ productId: node.productId }));
      this.store.dispatch(ProductStructureActions.loadDetail({ productId: node.productId }));
    });
  }

  // Operation: toggleNode (local UI state only)
  onToggleNode(node: ProductTreeNode): void {
    const id = node.productId;
    if (this.expandedNodeIds.has(id)) {
      this.expandedNodeIds.delete(id);
    } else {
      this.expandedNodeIds.add(id);
    }
  }

  isExpanded(node: ProductTreeNode): boolean {
    return this.expandedNodeIds.has(node.productId);
  }

  // Operation: save
  onSave(): void {
    if (this.form.invalid || this.currentDetail === null) {
      return;
    }
    const raw = this.form.getRawValue();
    this.store.dispatch(
      ProductStructureActions.saveProduct({
        productId: this.currentDetail.productId,
        productName: raw.productName,
        price: raw.price,
        description: raw.description,
        revision: this.currentDetail.revision,
      }),
    );
  }

  // Operation: cancel — restore the form from the confirmed Store value.
  onCancel(): void {
    this.guardDirty(() => {
      this.form.reset(
        this.currentDetail ? this.detailToFormValue(this.currentDetail) : this.emptyFormValue(),
      );
      this.store.dispatch(ProductStructureActions.cancelEdit());
    });
  }

  // Operation: reloadDetail
  onReload(): void {
    if (this.currentDetail === null) {
      return;
    }
    this.store.dispatch(
      ProductStructureActions.reloadDetail({ productId: this.currentDetail.productId }),
    );
  }

  trackByNodeId(_index: number, node: ProductTreeNode): string {
    return node.productId;
  }

  canDeactivate(): boolean | Observable<boolean> {
    if (!this.form.dirty) {
      return true;
    }
    return this.confirmation.confirm(this.confirmMessage);
  }

  private guardDirty(action: () => void): void {
    if (!this.form.dirty) {
      action();
      return;
    }
    this.confirmation
      .confirm(this.confirmMessage)
      .pipe(takeUntil(this.destroy$))
      .subscribe((confirmed) => {
        if (confirmed) {
          this.form.markAsPristine();
          action();
        }
      });
  }

  private applyEditPermission(canUpdate: boolean): void {
    const productNameCtrl = this.form.get('productName');
    if (canUpdate) {
      productNameCtrl?.enable({ emitEvent: false });
    } else {
      productNameCtrl?.disable({ emitEvent: false });
    }
    const priceCtrl = this.form.get('price');
    if (canUpdate) {
      priceCtrl?.enable({ emitEvent: false });
    } else {
      priceCtrl?.disable({ emitEvent: false });
    }
    const descriptionCtrl = this.form.get('description');
    if (canUpdate) {
      descriptionCtrl?.enable({ emitEvent: false });
    } else {
      descriptionCtrl?.disable({ emitEvent: false });
    }
  }

  private buildTreePayload(): LoadTreePayload {
    const raw = this.searchForm ? this.searchForm.getRawValue() : this.emptySearchValue();
    return {
      keyword: raw.keyword,
      categoryId: raw.categoryId,
    };
  }

  private detailToFormValue(detail: ProductDetail): Record<string, unknown> {
    return {
      productName: detail.productName,
      productCode: detail.productCode,
      price: detail.price,
      description: detail.description,
      revision: detail.revision,
    };
  }

  private emptyFormValue(): Record<string, unknown> {
    return {
      productName: '',
      productCode: '',
      price: 0,
      description: null,
      revision: 0,
    };
  }

  private emptySearchValue(): Record<string, unknown> {
    return {
      keyword: '',
      categoryId: '',
    };
  }
}
