// AUTO-GENERATED FILE.
// Source: specs/product-structure.md
// Definition: screens/product-structure.yaml
// Do not edit this file directly.
import { NgModule } from '@angular/core';
import { RouterModule, type Routes } from '@angular/router';

import { ProductStructureComponent } from './pages/product-structure/product-structure.component';
import { unsavedChangesGuard } from './guards/unsaved-changes.guard';

// A reference (view) permission guard can be attached here via `canActivate`
// using the project's existing permission guard, e.g. canActivate: [viewGuard].
const routes: Routes = [
  {
    path: '',
    component: ProductStructureComponent,
    canDeactivate: [unsavedChangesGuard],
  },
];

@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule],
})
export class ProductStructureRoutingModule {}
