// AUTO-GENERATED FILE.
// Source: specs/product-structure.md
// Definition: screens/product-structure.yaml
// Do not edit this file directly.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { ReactiveFormsModule } from '@angular/forms';
import { EffectsModule } from '@ngrx/effects';
import { StoreModule } from '@ngrx/store';

import { ProductStructureComponent } from './pages/product-structure/product-structure.component';
import { ProductStructureEffects } from './store/product-structure.effects';
import { productStructureReducer } from './store/product-structure.reducer';
import { productStructureFeatureKey } from './store/product-structure.state';
import { ProductStructureService } from './services/product-structure.service';
import { ProductStructureRoutingModule } from './product-structure-routing.module';

@NgModule({
  declarations: [ProductStructureComponent],
  imports: [
    CommonModule,
    ReactiveFormsModule,
    ProductStructureRoutingModule,
    StoreModule.forFeature(productStructureFeatureKey, productStructureReducer),
    EffectsModule.forFeature([ProductStructureEffects]),
  ],
  providers: [ProductStructureService],
})
export class ProductStructureModule {}
