// AUTO-GENERATED FILE.
// Source: specs/product-structure/
// Definition: specs/product-structure/resolved-screen.yaml
// Do not edit this file directly.
import { HttpClient, HttpParams } from '@angular/common/http';
import { Injectable, inject } from '@angular/core';
import { Observable } from 'rxjs';

import type { ProductStructureApiRequest } from '../models/product-structure-api.models';
import type { ProductDetailApiRequest } from '../models/product-structure-api.models';
import type { ProductUpdateApiRequest } from '../models/product-structure-api.models';
import type { ProductTreeResponseDto } from '../models/product-structure-api.models';
import type { ProductTreeNodeDto } from '../models/product-structure-api.models';
import type { ProductDetailApiResponse } from '../models/product-structure-api.models';

@Injectable({ providedIn: 'root' })
export class ProductStructureApiService {
  private readonly http = inject(HttpClient);

  loadTree(request: ProductStructureApiRequest): Observable<ProductTreeResponseDto> {
    let params = new HttpParams();
    if (request.keyword !== undefined && request.keyword !== null && request.keyword !== '') {
      params = params.set('keyword', String(request.keyword));
    }
    if (
      request.categoryId !== undefined &&
      request.categoryId !== null &&
      request.categoryId !== ''
    ) {
      params = params.set('categoryId', String(request.categoryId));
    }
    return this.http.get<ProductTreeResponseDto>(`/api/products/tree`, { params });
  }

  loadDetail(request: ProductDetailApiRequest): Observable<ProductDetailApiResponse> {
    return this.http.get<ProductDetailApiResponse>(`/api/products/${request.productId}`);
  }

  updateDetail(request: ProductUpdateApiRequest): Observable<ProductDetailApiResponse> {
    return this.http.put<ProductDetailApiResponse>(`/api/products/${request.productId}`, request);
  }
}
