// AUTO-GENERATED FILE.
// Source: specs/product-structure/
// Definition: specs/product-structure/resolved-screen.yaml
// Do not edit this file directly.
import { ChangeDetectionStrategy, Component, EventEmitter, Input, Output } from '@angular/core';

import type { NodeSelection } from '../../models/product-structure-view.models';
import type { ProductTreeNode } from '../../models/product-structure-view.models';

@Component({
  selector: 'app-product-tree-node',
  standalone: false,
  templateUrl: './product-tree-node.component.html',
  styleUrl: './product-tree-node.component.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ProductTreeNodeComponent {
  @Input({ required: true })
  node!: ProductTreeNode;

  @Input({ required: true })
  selectedComponentId!: string;

  @Input({ required: true })
  expandedNodeIds!: string;

  @Input({ required: true })
  disabled!: boolean;

  @Output()
  readonly nodeSelected = new EventEmitter<NodeSelection>();

  @Output()
  readonly nodeToggled = new EventEmitter<string>();
}
