// AUTO-GENERATED FILE.
// Source: specs/product-structure.md
// Definition: screens/product-structure.yaml
// Do not edit this file directly.
import { HttpClient, HttpParams } from '@angular/common/http';
import { Injectable, inject } from '@angular/core';
import { type Observable } from 'rxjs';

import type {
  ProductStructureApiRequest,
  ProductTreeResponseDto,
  ProductTreeNodeDto,
  ProductDetailApiResponse,
  ProductUpdateApiRequest,
} from '../models/api';

/**
 * HTTP access layer. This class only builds requests and returns raw responses.
 * It never touches the Store, dispatches actions, navigates, or shows dialogs.
 */
@Injectable()
export class ProductStructureService {
  private readonly http = inject(HttpClient);

  /** 検索条件でツリーを取得する (GET /api/products/tree) */
  loadTree(request: ProductStructureApiRequest): Observable<ProductTreeResponseDto> {
    const url = `/api/products/tree`;
    let params = new HttpParams();
    for (const [key, value] of Object.entries(request as unknown as Record<string, unknown>)) {
      if (value !== null && value !== undefined) {
        params = params.set(key, String(value));
      }
    }
    return this.http.get<ProductTreeResponseDto>(url, { params });
  }

  /** 製品詳細を取得する (GET /api/products/{productId}) */
  loadDetail(productId: string): Observable<ProductDetailApiResponse> {
    const url = `/api/products/${productId}`;
    return this.http.get<ProductDetailApiResponse>(url);
  }

  /** 製品詳細を更新する (PUT /api/products/{productId}) */
  updateDetail(
    productId: string,
    request: ProductUpdateApiRequest,
  ): Observable<ProductDetailApiResponse> {
    const url = `/api/products/${productId}`;
    return this.http.put<ProductDetailApiResponse>(url, request);
  }
}
