// AUTO-GENERATED FILE.
// Source: specs/product-structure.md
// Definition: screens/product-structure.yaml
// Do not edit this file directly.
import { HttpClientTestingModule, HttpTestingController } from '@angular/common/http/testing';
import { TestBed } from '@angular/core/testing';

import { ProductStructureService } from './product-structure.service';

describe('ProductStructureService', () => {
  let service: ProductStructureService;
  let httpMock: HttpTestingController;

  beforeEach(() => {
    TestBed.configureTestingModule({
      imports: [HttpClientTestingModule],
      providers: [ProductStructureService],
    });
    service = TestBed.inject(ProductStructureService);
    httpMock = TestBed.inject(HttpTestingController);
  });

  afterEach(() => httpMock.verify());

  // The Service only performs HTTP; it never touches the Store.
  it('loadDetail should issue a GET request', () => {
    service.loadDetail('P1').subscribe();
    const req = httpMock.expectOne('/api/products/P1');
    expect(req.request.method).toBe('GET');
    req.flush({});
  });
});
