// AUTO-GENERATED FILE.
// Source: specs/product-structure.md
// Definition: screens/product-structure.yaml
// Do not edit this file directly.
import { TestBed } from '@angular/core/testing';
import { type ActivatedRouteSnapshot, type RouterStateSnapshot } from '@angular/router';

import { unsavedChangesGuard } from './unsaved-changes.guard';
import type { ProductStructureComponent } from '../pages/product-structure/product-structure.component';

describe('unsavedChangesGuard', () => {
  const route = {} as ActivatedRouteSnapshot;
  const state = {} as RouterStateSnapshot;

  // Test: test-unsaved — deactivation is delegated to the component's guard.
  it('should allow deactivation when the component reports no unsaved changes', () => {
    const component = { canDeactivate: () => true } as ProductStructureComponent;
    const result = TestBed.runInInjectionContext(() =>
      unsavedChangesGuard(component, route, state, state),
    );
    expect(result).toBe(true);
  });

  it('should block deactivation when the component reports unsaved changes', () => {
    const component = { canDeactivate: () => false } as ProductStructureComponent;
    const result = TestBed.runInInjectionContext(() =>
      unsavedChangesGuard(component, route, state, state),
    );
    expect(result).toBe(false);
  });
});
