// AUTO-GENERATED FILE.
// Source: specs/product-structure.md
// Definition: screens/product-structure.yaml
// Do not edit this file directly.
import { type CanDeactivateFn } from '@angular/router';
import { type Observable } from 'rxjs';

import type { ProductStructureComponent } from '../pages/product-structure/product-structure.component';

/** Any component guarded by this function must expose `canDeactivate`. */
export interface CanComponentDeactivate {
  canDeactivate: () => boolean | Observable<boolean>;
}

/**
 * Prevents navigation away from the screen while there are unsaved changes.
 * The confirmation itself is delegated to the component so the shared dialog
 * implementation can be swapped without changing the guard.
 */
export const unsavedChangesGuard: CanDeactivateFn<ProductStructureComponent> = (component) =>
  component.canDeactivate();
