// AUTO-GENERATED FILE.
// Source: specs/product-structure/
// Definition: specs/product-structure/resolved-screen.yaml
// Do not edit this file directly.
import {
  ChangeDetectionStrategy,
  Component,
  EventEmitter,
  Input,
  Output,
  OnChanges,
  SimpleChanges,
} from '@angular/core';
import { FormGroup } from '@angular/forms';

import type { ApiError } from '../../models/product-structure-common.models';
import type { ReloadDetailPayload } from '../../models/product-structure-payload.models';
import type { SaveProductPayload } from '../../models/product-structure-payload.models';
import type { ProductDetail } from '../../models/product-structure-view.models';
import {
  createProductDetailForm,
  type ProductDetailForm,
} from '../../forms/product-detail-form.factory';

@Component({
  selector: 'app-product-detail-form',
  standalone: false,
  templateUrl: './product-detail-form.component.html',
  styleUrl: './product-detail-form.component.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ProductDetailFormComponent implements OnChanges {
  @Input({ required: true })
  detail!: ProductDetail;

  @Input({ required: true })
  selectedComponentId!: string;

  @Input({ required: true })
  readonly!: boolean;

  @Input({ required: true })
  loading!: boolean;

  @Input({ required: true })
  saving!: boolean;

  @Input({ required: true })
  saveError!: ApiError;

  @Input({ required: true })
  concurrentUpdate!: boolean;

  @Output()
  readonly saveRequested = new EventEmitter<SaveProductPayload>();

  @Output()
  readonly cancelRequested = new EventEmitter<void>();

  @Output()
  readonly reloadRequested = new EventEmitter<ReloadDetailPayload>();

  @Output()
  readonly dirtyChanged = new EventEmitter<boolean>();

  form!: FormGroup<ProductDetailForm>;

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['detail'] && this.detail) {
      this.form = createProductDetailForm(this.detail);
    }
  }

  emitSave(): void {
    this.saveRequested.emit({
      componentId: this.selectedComponentId,
      productId: this.detail.productId,
      productName: this.form.controls.productName.getRawValue(),
      price: Number(this.form.controls.price.getRawValue()),
      description: this.form.controls.description.getRawValue(),
      revision: Number(this.form.controls.revision.getRawValue()),
    });
  }
}
