// AUTO-GENERATED FILE.
// Source: specs/product-structure/
// Definition: specs/product-structure/resolved-screen.yaml
// Do not edit this file directly.
import { AbstractControl, ValidationErrors, ValidatorFn } from '@angular/forms';

export function integerValidator(): ValidatorFn {
  return (control: AbstractControl): ValidationErrors | null => {
    const value = control.value;
    if (value === null || value === undefined || value === '') {
      return null;
    }
    return Number.isInteger(Number(value)) ? null : { integer: true };
  };
}
