import fs from 'fs-extra';
import { parse, stringify } from 'yaml';

import type { ScreenDefinition } from '../types/screen-definition.js';
import { GeneratorError } from '../utils/errors.js';

/** Serializes a ScreenDefinition to a deterministic YAML document. */
export function serializeScreen(definition: ScreenDefinition): string {
  const header = [
    '# AUTO-GENERATED FILE.',
    '# Generated from a Markdown screen specification.',
    '# Do not edit this file directly; edit the source Markdown instead.',
    '',
  ].join('\n');
  const body = stringify(definition, {
    indent: 2,
    lineWidth: 0,
    sortMapEntries: false,
  });
  return `${header}${body}`;
}

export async function writeScreenYaml(
  definition: ScreenDefinition,
  outputPath: string,
): Promise<void> {
  await fs.ensureDir(outputPath.replace(/[/\\][^/\\]+$/, ''));
  await fs.writeFile(outputPath, serializeScreen(definition), 'utf8');
}

/**
 * Loads and parses a screen.yaml file. Uses the safe YAML parser which never
 * executes arbitrary code and rejects unknown custom tags.
 */
export async function loadScreenYaml(inputPath: string): Promise<ScreenDefinition> {
  const content = await fs.readFile(inputPath, 'utf8');
  let parsed: unknown;
  try {
    parsed = parse(content, { strict: true });
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    throw new GeneratorError('SCHEMA_VALIDATION_ERROR', `Invalid YAML: ${message}`, {
      target: inputPath,
      fix: 'Ensure the file is valid YAML produced by the convert command.',
    });
  }
  if (typeof parsed !== 'object' || parsed === null) {
    throw new GeneratorError('SCHEMA_VALIDATION_ERROR', 'screen.yaml is empty.', {
      target: inputPath,
    });
  }
  return parsed as ScreenDefinition;
}
