// AUTO-GENERATED FILE.
// Source: specs/product-structure.md
// Definition: screens/product-structure.yaml
// Do not edit this file directly.
import { createAction, props } from '@ngrx/store';

import type {
  ApiErrorPayload,
  LoadDetailPayload,
  LoadDetailSuccessPayload,
  LoadPermissionsSuccessPayload,
  LoadTreePayload,
  LoadTreeSuccessPayload,
  ReloadDetailPayload,
  SaveProductPayload,
  SaveProductSuccessPayload,
  SelectNodePayload,
  SetPendingOperationPayload,
} from '../models/actions';

// Operation: enterPage / category: page
export const enterPage = createAction('[Product Structure] Enter Page');

// Operation: enterPage / category: permission
export const loadPermissions = createAction('[Product Structure] Load Permissions');

// Operation: (chained) / category: permission
export const loadPermissionsSuccess = createAction(
  '[Product Structure] Load Permissions Success',
  props<LoadPermissionsSuccessPayload>(),
);

// Operation: (chained) / category: permission
export const loadPermissionsFailure = createAction(
  '[Product Structure] Load Permissions Failure',
  props<ApiErrorPayload>(),
);

// Operation: search / category: tree
export const loadTree = createAction('[Product Structure] Load Tree', props<LoadTreePayload>());

// Operation: (chained) / category: tree
export const loadTreeSuccess = createAction(
  '[Product Structure] Load Tree Success',
  props<LoadTreeSuccessPayload>(),
);

// Operation: (chained) / category: tree
export const loadTreeFailure = createAction(
  '[Product Structure] Load Tree Failure',
  props<ApiErrorPayload>(),
);

// Operation: clear / category: search
export const clearSearch = createAction('[Product Structure] Clear Search');

// Operation: selectNode / category: tree
export const selectNode = createAction(
  '[Product Structure] Select Node',
  props<SelectNodePayload>(),
);

// Operation: selectNode / category: detail
export const loadDetail = createAction(
  '[Product Structure] Load Detail',
  props<LoadDetailPayload>(),
);

// Operation: (chained) / category: detail
export const loadDetailSuccess = createAction(
  '[Product Structure] Load Detail Success',
  props<LoadDetailSuccessPayload>(),
);

// Operation: (chained) / category: detail
export const loadDetailFailure = createAction(
  '[Product Structure] Load Detail Failure',
  props<ApiErrorPayload>(),
);

// Operation: save / category: detail
export const saveProduct = createAction(
  '[Product Structure] Save Product',
  props<SaveProductPayload>(),
);

// Operation: (chained) / category: detail
export const saveProductSuccess = createAction(
  '[Product Structure] Save Product Success',
  props<SaveProductSuccessPayload>(),
);

// Operation: (chained) / category: detail
export const saveProductFailure = createAction(
  '[Product Structure] Save Product Failure',
  props<ApiErrorPayload>(),
);

// Operation: save / category: detail
export const concurrentUpdateDetected = createAction(
  '[Product Structure] Concurrent Update Detected',
  props<ApiErrorPayload>(),
);

// Operation: reloadDetail / category: detail
export const reloadDetail = createAction(
  '[Product Structure] Reload Detail',
  props<ReloadDetailPayload>(),
);

// Operation: (chained) / category: detail
export const reloadDetailSuccess = createAction(
  '[Product Structure] Reload Detail Success',
  props<LoadDetailSuccessPayload>(),
);

// Operation: cancel / category: detail
export const cancelEdit = createAction('[Product Structure] Cancel Edit');

// Operation: (chained) / category: unsaved
export const setPendingOperation = createAction(
  '[Product Structure] Set Pending Operation',
  props<SetPendingOperationPayload>(),
);

// Operation: (chained) / category: unsaved
export const clearPendingOperation = createAction('[Product Structure] Clear Pending Operation');
