// AUTO-GENERATED FILE.
// Source: specs/product-structure.md
// Definition: screens/product-structure.yaml
// Do not edit this file directly.
import * as ProductStructureActions from './product-structure.actions';
import { productStructureReducer } from './product-structure.reducer';
import { initialProductStructureState } from './product-structure.state';

describe('productStructureReducer', () => {
  it('should return the initial state for an unknown action', () => {
    const state = productStructureReducer(initialProductStructureState, { type: 'unknown' });
    expect(state).toEqual(initialProductStructureState);
  });

  // Test: loadTreeSuccess stores the returned nodes and clears loading.
  it('should store tree nodes on loadTreeSuccess', () => {
    const nodes = [
      {
        productId: 'value',
        productName: 'value',
        productCode: 'value',
        parentId: 'value',
        children: [],
      },
    ];
    const state = productStructureReducer(
      initialProductStructureState,
      ProductStructureActions.loadTreeSuccess({ nodes }),
    );
    expect(state.treeNodes.length).toBe(1);
    expect(state.loading).toBe(false);
  });

  // Test: test-concurrent — concurrentUpdateDetected raises the concurrent flag.
  it('should set concurrentUpdate on concurrentUpdateDetected', () => {
    const state = productStructureReducer(
      initialProductStructureState,
      ProductStructureActions.concurrentUpdateDetected({
        error: {
          code: 'CONCURRENT_UPDATE',
          message: '他の利用者によって製品情報が更新されています。最新情報を再取得してください。',
        },
      }),
    );
    expect(state.concurrentUpdate).toBe(true);
    expect(state.saving).toBe(false);
  });
});
