// AUTO-GENERATED FILE.
// Source: specs/product-structure.md
// Definition: screens/product-structure.yaml
// Do not edit this file directly.
import type { ProductTreeNode, ProductDetail, ApiError, PendingOperation } from '../models/store';

export const productStructureFeatureKey = 'productStructure';

export interface ProductStructureState {
  /** 構成ツリー */
  treeNodes: ProductTreeNode[];
  /** 選択中のノードID */
  selectedNodeId: string | null;
  /** 選択中の製品詳細 */
  detail: ProductDetail | null;
  /** ローディング状態 */
  loading: boolean;
  /** 保存処理中 */
  saving: boolean;
  /** APIエラー */
  error: ApiError | null;
  /** 同時更新の発生状態 */
  concurrentUpdate: boolean;
  /** 保有権限コード */
  permissions: string[];
  /** 確認待ちの保留操作 */
  pendingOperation: PendingOperation | null;
}

export const initialProductStructureState: ProductStructureState = {
  treeNodes: [],
  selectedNodeId: null,
  detail: null,
  loading: false,
  saving: false,
  error: null,
  concurrentUpdate: false,
  permissions: [],
  pendingOperation: null,
};
