// AUTO-GENERATED FILE.
// Source: specs/product-structure.md
// Definition: screens/product-structure.yaml
// Do not edit this file directly.
import { createReducer, on } from '@ngrx/store';

import * as ProductStructureActions from './product-structure.actions';
import {
  initialProductStructureState,
  type ProductStructureState,
} from './product-structure.state';

export const productStructureReducer = createReducer(
  initialProductStructureState,
  on(ProductStructureActions.enterPage, (state) => ({
    ...state,
    loading: true,
    error: null,
  })),
  on(ProductStructureActions.loadPermissionsSuccess, (state, action) => ({
    ...state,
    permissions: action.permissions,
  })),
  on(ProductStructureActions.loadPermissionsFailure, (state, action) => ({
    ...state,
    error: action.error,
  })),
  on(ProductStructureActions.loadTree, (state) => ({
    ...state,
    loading: true,
    error: null,
  })),
  on(ProductStructureActions.loadTreeSuccess, (state, action) => ({
    ...state,
    treeNodes: action.nodes,
    loading: false,
  })),
  on(ProductStructureActions.loadTreeFailure, (state, action) => ({
    ...state,
    error: action.error,
    loading: false,
  })),
  on(ProductStructureActions.clearSearch, (state) => ({
    ...state,
    selectedNodeId: null,
    detail: null,
  })),
  on(ProductStructureActions.selectNode, (state, action) => ({
    ...state,
    selectedNodeId: action.productId,
  })),
  on(ProductStructureActions.loadDetail, (state) => ({
    ...state,
    loading: true,
    error: null,
  })),
  on(ProductStructureActions.loadDetailSuccess, (state, action) => ({
    ...state,
    detail: action.detail,
    loading: false,
    concurrentUpdate: false,
  })),
  on(ProductStructureActions.loadDetailFailure, (state, action) => ({
    ...state,
    error: action.error,
    loading: false,
  })),
  on(ProductStructureActions.saveProduct, (state) => ({
    ...state,
    saving: true,
    error: null,
  })),
  on(ProductStructureActions.saveProductSuccess, (state, action) => ({
    ...state,
    detail: action.detail,
    saving: false,
    concurrentUpdate: false,
  })),
  on(ProductStructureActions.saveProductFailure, (state, action) => ({
    ...state,
    error: action.error,
    saving: false,
  })),
  on(ProductStructureActions.concurrentUpdateDetected, (state, action) => ({
    ...state,
    concurrentUpdate: true,
    saving: false,
    error: action.error,
  })),
  on(ProductStructureActions.reloadDetail, (state) => ({
    ...state,
    loading: true,
  })),
  on(ProductStructureActions.reloadDetailSuccess, (state, action) => ({
    ...state,
    detail: action.detail,
    loading: false,
    concurrentUpdate: false,
  })),
  on(ProductStructureActions.setPendingOperation, (state, action) => ({
    ...state,
    pendingOperation: action.pending,
  })),
  on(ProductStructureActions.clearPendingOperation, (state) => ({
    ...state,
    pendingOperation: null,
  })),
);
