// AUTO-GENERATED FILE.
// Source: specs/product-structure.md
// Definition: screens/product-structure.yaml
// Do not edit this file directly.
import { TestBed } from '@angular/core/testing';
import { provideMockActions } from '@ngrx/effects/testing';
import { type Observable, of } from 'rxjs';

import { PermissionService } from '../../../core/services/permission.service';
import { ProductStructureService } from '../services/product-structure.service';
import * as ProductStructureActions from './product-structure.actions';
import { ProductStructureEffects } from './product-structure.effects';

describe('ProductStructureEffects', () => {
  let actions$: Observable<unknown>;
  const serviceMock = {
    loadTree: jasmine.createSpy('loadTree'),
    loadDetail: jasmine.createSpy('loadDetail'),
    updateDetail: jasmine.createSpy('updateDetail'),
  };
  const permissionMock = {
    getPermissions: jasmine.createSpy('getPermissions').and.returnValue(of(['PRODUCT_VIEW'])),
  };

  beforeEach(() => {
    TestBed.configureTestingModule({
      providers: [
        ProductStructureEffects,
        provideMockActions(() => actions$),
        { provide: ProductStructureService, useValue: serviceMock },
        { provide: PermissionService, useValue: permissionMock },
      ],
    });
  });

  // Test: test-search — loadTree effect calls the Service and maps to success.
  it('should call the service and emit loadTreeSuccess', (done) => {
    serviceMock.loadTree.and.returnValue(of({ nodes: [] }));
    actions$ = of(ProductStructureActions.loadTree({ keyword: '', categoryId: null }));
    const effects = TestBed.inject(ProductStructureEffects);

    effects.loadTree$.subscribe((action) => {
      expect(serviceMock.loadTree).toHaveBeenCalled();
      expect(action.type).toBe(ProductStructureActions.loadTreeSuccess.type);
      done();
    });
  });
});
