// AUTO-GENERATED FILE.
// Source: specs/product-structure.md
// Definition: screens/product-structure.yaml
// Do not edit this file directly.
import { createFeatureSelector, createSelector } from '@ngrx/store';

import { productStructureFeatureKey, type ProductStructureState } from './product-structure.state';

export const VIEW_PERMISSION = 'PRODUCT_VIEW';
export const UPDATE_PERMISSION = 'PRODUCT_UPDATE';

export const selectFeature = createFeatureSelector<ProductStructureState>(
  productStructureFeatureKey,
);

export const selectTreeNodes = createSelector(selectFeature, (state) => state.treeNodes);

export const selectSelectedNodeId = createSelector(selectFeature, (state) => state.selectedNodeId);

export const selectDetail = createSelector(selectFeature, (state) => state.detail);

export const selectLoading = createSelector(selectFeature, (state) => state.loading);

export const selectSaving = createSelector(selectFeature, (state) => state.saving);

export const selectError = createSelector(selectFeature, (state) => state.error);

export const selectConcurrentUpdate = createSelector(
  selectFeature,
  (state) => state.concurrentUpdate,
);

export const selectPermissions = createSelector(selectFeature, (state) => state.permissions);

export const selectPendingOperation = createSelector(
  selectFeature,
  (state) => state.pendingOperation,
);

// Derived selectors — the Component must not re-implement these predicates.
export const selectIsEmpty = createSelector(selectTreeNodes, (nodes) => nodes.length === 0);

export const selectHasError = createSelector(selectError, (error) => error !== null);

export const selectErrorMessage = createSelector(selectError, (error) =>
  error ? error.message : null,
);

export const selectCanView = createSelector(selectPermissions, (permissions) =>
  permissions.includes(VIEW_PERMISSION),
);

export const selectCanUpdate = createSelector(selectPermissions, (permissions) =>
  permissions.includes(UPDATE_PERMISSION),
);

export const selectShowConcurrentUpdate = createSelector(
  selectConcurrentUpdate,
  (concurrentUpdate) => concurrentUpdate === true,
);

export const selectCanSave = createSelector(
  selectCanUpdate,
  selectSaving,
  selectDetail,
  (canUpdate, saving, detail) => canUpdate && !saving && detail !== null,
);

export const selectViewModel = createSelector(
  selectTreeNodes,
  selectSelectedNodeId,
  selectDetail,
  selectLoading,
  selectSaving,
  selectError,
  selectErrorMessage,
  selectConcurrentUpdate,
  selectIsEmpty,
  selectCanView,
  selectCanUpdate,
  selectCanSave,
  selectShowConcurrentUpdate,
  (
    treeNodes,
    selectedNodeId,
    detail,
    loading,
    saving,
    error,
    errorMessage,
    concurrentUpdate,
    isEmpty,
    canView,
    canUpdate,
    canSave,
    showConcurrentUpdate,
  ) => ({
    treeNodes,
    selectedNodeId,
    detail,
    loading,
    saving,
    error,
    errorMessage,
    concurrentUpdate,
    isEmpty,
    canView,
    canUpdate,
    canSave,
    showConcurrentUpdate,
  }),
);
