// AUTO-GENERATED FILE.
// Source: specs/product-structure.md
// Definition: screens/product-structure.yaml
// Do not edit this file directly.
import { HttpErrorResponse } from '@angular/common/http';
import { Injectable, inject } from '@angular/core';
import { Actions, createEffect, ofType } from '@ngrx/effects';
import { type Action } from '@ngrx/store';
import { of } from 'rxjs';
import { catchError, exhaustMap, map, switchMap } from 'rxjs/operators';

import { PermissionService } from '../../../core/services/permission.service';
import {
  mapDetail,
  mapTreeResponse,
  toApiError,
  toTreeRequest,
  toUpdateRequest,
} from '../mappers/product-structure.mapper';
import { ProductStructureService } from '../services/product-structure.service';
import * as ProductStructureActions from './product-structure.actions';

/**
 * Side-effect layer. Effects listen to actions, call the Service, map DTOs to
 * view/store models, and emit success/failure actions. They never touch the
 * Store or the Component directly and never use HttpClient.
 */
@Injectable()
export class ProductStructureEffects {
  private readonly actions$ = inject(Actions);
  private readonly service = inject(ProductStructureService);
  private readonly permissionService = inject(PermissionService);

  // Operation: enterPage — load the current user's permissions.
  loadPermissions$ = createEffect(() =>
    this.actions$.pipe(
      ofType(ProductStructureActions.enterPage, ProductStructureActions.loadPermissions),
      switchMap(() =>
        this.permissionService.getPermissions().pipe(
          map((permissions) => ProductStructureActions.loadPermissionsSuccess({ permissions })),
          catchError((error) =>
            of(ProductStructureActions.loadPermissionsFailure({ error: toApiError(error) })),
          ),
        ),
      ),
    ),
  );

  // Operation: search — reload the tree; switchMap drops stale results.
  loadTree$ = createEffect(() =>
    this.actions$.pipe(
      ofType(ProductStructureActions.loadTree),
      switchMap((action) =>
        this.service.loadTree(toTreeRequest(action)).pipe(
          map((response) =>
            ProductStructureActions.loadTreeSuccess({ nodes: mapTreeResponse(response) }),
          ),
          catchError((error) =>
            of(ProductStructureActions.loadTreeFailure({ error: toApiError(error) })),
          ),
        ),
      ),
    ),
  );

  // Operation: selectNode — load the selected product detail.
  loadDetail$ = createEffect(() =>
    this.actions$.pipe(
      ofType(ProductStructureActions.loadDetail),
      switchMap((action) =>
        this.service.loadDetail(action.productId).pipe(
          map((response) =>
            ProductStructureActions.loadDetailSuccess({ detail: mapDetail(response) }),
          ),
          catchError((error) =>
            of(ProductStructureActions.loadDetailFailure({ error: toApiError(error) })),
          ),
        ),
      ),
    ),
  );

  // Operation: reloadDetail — re-fetch after a concurrent-update conflict.
  reloadDetail$ = createEffect(() =>
    this.actions$.pipe(
      ofType(ProductStructureActions.reloadDetail),
      switchMap((action) =>
        this.service.loadDetail(action.productId).pipe(
          map((response) =>
            ProductStructureActions.reloadDetailSuccess({ detail: mapDetail(response) }),
          ),
          catchError((error) =>
            of(ProductStructureActions.loadDetailFailure({ error: toApiError(error) })),
          ),
        ),
      ),
    ),
  );

  // Operation: save — exhaustMap ignores repeated Save presses while saving.
  saveProduct$ = createEffect(() =>
    this.actions$.pipe(
      ofType(ProductStructureActions.saveProduct),
      exhaustMap((action) =>
        this.service.updateDetail(action.productId, toUpdateRequest(action)).pipe(
          map((response) =>
            ProductStructureActions.saveProductSuccess({ detail: mapDetail(response) }),
          ),
          catchError((error) => of(this.toSaveFailure(error))),
        ),
      ),
    ),
  );

  private toSaveFailure(error: unknown): Action {
    const apiError = toApiError(error);
    if (
      error instanceof HttpErrorResponse &&
      error.status === 409 &&
      apiError.code === 'CONCURRENT_UPDATE'
    ) {
      return ProductStructureActions.concurrentUpdateDetected({ error: apiError });
    }
    return ProductStructureActions.saveProductFailure({ error: apiError });
  }
}
