// AUTO-GENERATED FILE.
// Source: specs/product-structure.md
// Definition: screens/product-structure.yaml
// Do not edit this file directly.
import {
  UPDATE_PERMISSION,
  VIEW_PERMISSION,
  selectCanUpdate,
  selectCanView,
  selectIsEmpty,
} from './product-structure.selectors';
import { initialProductStructureState } from './product-structure.state';

describe('product-structure selectors', () => {
  // Test: empty tree is reported by the selector, not the component.
  it('selectIsEmpty should be true for the initial state', () => {
    expect(selectIsEmpty.projector(initialProductStructureState.treeNodes)).toBe(true);
  });

  // Test: test-readonly — canUpdate is derived from permissions in a selector.
  it('selectCanUpdate should reflect the UPDATE permission', () => {
    expect(selectCanUpdate.projector([VIEW_PERMISSION])).toBe(false);
    expect(selectCanUpdate.projector([VIEW_PERMISSION, UPDATE_PERMISSION])).toBe(true);
  });

  it('selectCanView should reflect the VIEW permission', () => {
    expect(selectCanView.projector([VIEW_PERMISSION])).toBe(true);
    expect(selectCanView.projector([])).toBe(false);
  });
});
