// AUTO-GENERATED FILE.
// Source: specs/product-structure/
// Definition: specs/product-structure/resolved-screen.yaml
// Do not edit this file directly.
import { FormControl, FormGroup, Validators } from '@angular/forms';

import { integerValidator } from '../validators/integer.validator';
import { uuidValidator } from '../validators/uuid.validator';
import type { ProductSearchCondition } from '../models/product-structure-view.models';

export interface ProductSearchForm {
  keyword: FormControl<string>;
  categoryId: FormControl<string | null>;
}

export function createProductSearchForm(
  initialValue: ProductSearchCondition,
): FormGroup<ProductSearchForm> {
  return new FormGroup<ProductSearchForm>({
    keyword: new FormControl(String(initialValue.keyword ?? ''), {
      nonNullable: true,
      validators: [Validators.maxLength(100)],
    }),
    categoryId: new FormControl(initialValue.categoryId ?? null, {
      nonNullable: false,
      validators: [uuidValidator()],
    }),
  });
}
