// AUTO-GENERATED FILE.
// Source: specs/product-structure/
// Definition: specs/product-structure/resolved-screen.yaml
// Do not edit this file directly.
import { FormControl, FormGroup, Validators } from '@angular/forms';

import { integerValidator } from '../validators/integer.validator';
import { uuidValidator } from '../validators/uuid.validator';
import type { ProductDetail } from '../models/product-structure-view.models';

export interface ProductDetailForm {
  productName: FormControl<string>;
  productCode: FormControl<string>;
  price: FormControl<string>;
  description: FormControl<string>;
  revision: FormControl<string>;
}

export function createProductDetailForm(initialValue: ProductDetail): FormGroup<ProductDetailForm> {
  return new FormGroup<ProductDetailForm>({
    productName: new FormControl(String(initialValue.productName ?? ''), {
      nonNullable: true,
      validators: [Validators.maxLength(200), Validators.maxLength(255), Validators.required],
    }),
    productCode: new FormControl(String(initialValue.productCode ?? ''), {
      nonNullable: true,
      validators: [],
    }),
    price: new FormControl(String(initialValue.price ?? ''), {
      nonNullable: true,
      validators: [
        Validators.max(999999999999),
        Validators.max(Number.MAX_SAFE_INTEGER),
        Validators.min(0),
        Validators.required,
        integerValidator(),
      ],
    }),
    description: new FormControl(String(initialValue.description ?? ''), {
      nonNullable: true,
      validators: [Validators.maxLength(2000), Validators.maxLength(255)],
    }),
    revision: new FormControl(String(initialValue.revision ?? ''), {
      nonNullable: true,
      validators: [],
    }),
  });
}
