import { fileURLToPath } from 'node:url';
import path from 'node:path';

import fg from 'fast-glob';
import fs from 'fs-extra';

import type { FileChange, RenderedFile } from '../types/generator-options.js';
import { GeneratorError } from '../utils/errors.js';
import { logger } from '../utils/logger.js';

const currentDir = path.dirname(fileURLToPath(import.meta.url));
export const PROJECT_ROOT = path.resolve(currentDir, '../../../..');

const AUTO_GENERATED_MARKER = 'AUTO-GENERATED FILE';

/** Resolves a path and guarantees it never escapes the project root. */
export function resolveWithinRoot(target: string): string {
  const resolved = path.resolve(PROJECT_ROOT, target);
  const relative = path.relative(PROJECT_ROOT, resolved);
  if (relative.startsWith('..') || path.isAbsolute(relative)) {
    throw new GeneratorError(
      'PATH_SECURITY_ERROR',
      `Output path escapes the project root: ${target}`,
      { target, fix: 'Choose an output path inside the project directory.' },
    );
  }
  return resolved;
}

export function toRelativeFromRoot(absolutePath: string): string {
  return path.relative(PROJECT_ROOT, absolutePath).split(path.sep).join('/');
}

/** screens/<md-basename>.yaml, resolved inside the project root. */
export function defaultScreenPath(inputMarkdownPath: string): string {
  const base = path.basename(inputMarkdownPath).replace(/\.md$/i, '');
  return resolveWithinRoot(path.join('screens', `${base}.yaml`));
}

/** src/app/features/<feature-kebab>, resolved inside the project root. */
export function defaultCodeOutput(featureKebab: string): string {
  return resolveWithinRoot(path.join('src', 'app', 'features', featureKebab));
}

function isAutoGenerated(content: string): boolean {
  return content.includes(AUTO_GENERATED_MARKER);
}

async function listExistingGenerated(outputRootAbs: string): Promise<string[]> {
  if (!(await fs.pathExists(outputRootAbs))) {
    return [];
  }
  const entries = await fg('**/*', {
    cwd: outputRootAbs,
    onlyFiles: true,
    dot: false,
  });
  return entries.map((entry) => entry.split('/').join('/'));
}

export interface ResolveResult {
  changes: FileChange[];
  protectedFiles: string[];
}

/**
 * Compares the freshly rendered (already formatted) files against what is on
 * disk and produces the set of changes. Applies the overwrite policy:
 *  - files without the AUTO-GENERATED header are protected unless `force`
 *  - obsolete auto-generated files not in the new output are marked DELETE
 */
export async function resolveChanges(
  renderedFiles: RenderedFile[],
  outputRootAbs: string,
  force: boolean,
): Promise<ResolveResult> {
  resolveWithinRoot(outputRootAbs);
  const changes: FileChange[] = [];
  const protectedFiles: string[] = [];
  const renderedRelativeSet = new Set(renderedFiles.map((file) => file.relativePath));

  for (const file of renderedFiles) {
    const absolutePath = path.join(outputRootAbs, file.relativePath);
    resolveWithinRoot(absolutePath);
    const relativeFromRoot = toRelativeFromRoot(absolutePath);
    if (!(await fs.pathExists(absolutePath))) {
      changes.push({
        type: 'CREATE',
        relativePath: relativeFromRoot,
        absolutePath,
        nextContent: file.content,
      });
      continue;
    }
    const existing = await fs.readFile(absolutePath, 'utf8');
    if (existing === file.content) {
      changes.push({
        type: 'UNCHANGED',
        relativePath: relativeFromRoot,
        absolutePath,
        nextContent: null,
      });
      continue;
    }
    if (!isAutoGenerated(existing) && !force) {
      protectedFiles.push(relativeFromRoot);
      changes.push({
        type: 'UNCHANGED',
        relativePath: relativeFromRoot,
        absolutePath,
        nextContent: null,
      });
      continue;
    }
    changes.push({
      type: 'UPDATE',
      relativePath: relativeFromRoot,
      absolutePath,
      nextContent: file.content,
    });
  }

  const existingFiles = await listExistingGenerated(outputRootAbs);
  for (const relative of existingFiles) {
    if (renderedRelativeSet.has(relative)) {
      continue;
    }
    const absolutePath = path.join(outputRootAbs, relative);
    const content = await fs.readFile(absolutePath, 'utf8');
    if (isAutoGenerated(content)) {
      changes.push({
        type: 'DELETE',
        relativePath: toRelativeFromRoot(absolutePath),
        absolutePath,
        nextContent: null,
      });
    }
  }

  if (protectedFiles.length > 0) {
    for (const file of protectedFiles) {
      logger.warn(`Protected (no AUTO-GENERATED header, use --force to overwrite): ${file}`);
    }
  }

  changes.sort((a, b) => a.relativePath.localeCompare(b.relativePath));
  return { changes, protectedFiles };
}
