// AUTO-GENERATED FILE.
// Source: specs/product-structure/
// Definition: specs/product-structure/resolved-screen.yaml
// Do not edit this file directly.
import { inject } from '@angular/core';
import { CanActivateFn } from '@angular/router';
import { Store } from '@ngrx/store';
import { map, take } from 'rxjs';

import { selectProductStructureState } from '../store/product-structure.selectors';

export const productStructureAccessGuard: CanActivateFn = () => {
  const store = inject(Store);
  return store.select(selectProductStructureState).pipe(
    take(1),
    map(() => true),
  );
};
