// AUTO-GENERATED FILE.
// Source: specs/product-structure/
// Definition: specs/product-structure/resolved-screen.yaml
// Do not edit this file directly.
import { CanDeactivateFn } from '@angular/router';

export interface ProductStructureDeactivate {
  canDeactivate?: () => boolean;
}

export const productStructureDeactivateGuard: CanDeactivateFn<ProductStructureDeactivate> = (
  component,
) => component.canDeactivate?.() ?? true;
