// AUTO-GENERATED FILE.
// Source: specs/product-structure.md
// Definition: screens/product-structure.yaml
// Do not edit this file directly.
import type { ProductTreeNodeDto } from './product-tree-node-dto.model';

/** API DTO. Contains only fields exchanged over HTTP. */
export interface ProductTreeResponseDto {
  /** ツリーノード一覧 */
  nodes: ProductTreeNodeDto[];
}
