// AUTO-GENERATED FILE.
// Source: specs/product-structure.md
// Definition: screens/product-structure.yaml
// Do not edit this file directly.

/** API DTO. Contains only fields exchanged over HTTP. */
export interface ProductDetailApiResponse {
  /** 製品ID */
  productId: string;
  /** 製品名 */
  productName: string;
  /** 製品コード */
  productCode: string;
  /** 価格 */
  price: number;
  /** 説明 */
  description: string | null;
  /** リビジョン */
  revision: number;
}
