// AUTO-GENERATED FILE.
// Source: specs/product-structure.md
// Definition: screens/product-structure.yaml
// Do not edit this file directly.

/** API DTO. Contains only fields exchanged over HTTP. */
export interface ProductStructureApiRequest {
  /** 検索キーワード */
  keyword: string;
  /** カテゴリID */
  categoryId: string | null;
}
