// AUTO-GENERATED FILE.
// Source: specs/product-structure/
// Definition: specs/product-structure/resolved-screen.yaml
// Do not edit this file directly.
import { ChangeDetectionStrategy, Component, EventEmitter, Input, Output } from '@angular/core';

import type { ReloadDetailPayload } from '../../models/product-structure-payload.models';

@Component({
  selector: 'app-concurrent-update-message',
  standalone: false,
  templateUrl: './concurrent-update-message.component.html',
  styleUrl: './concurrent-update-message.component.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ConcurrentUpdateMessageComponent {
  @Input({ required: true })
  visible!: boolean;

  @Input({ required: true })
  message!: string;

  @Input({ required: true })
  loading!: boolean;

  @Input({ required: true })
  productId!: string;

  @Output()
  readonly reloadRequested = new EventEmitter<ReloadDetailPayload>();
}
