// AUTO-GENERATED FILE.
// Source: specs/product-structure/
// Definition: specs/product-structure/resolved-screen.yaml
// Do not edit this file directly.
import type { ProductStructureApiRequest } from '../models/product-structure-api.models';
import type { ProductDetailApiRequest } from '../models/product-structure-api.models';
import type { ProductUpdateApiRequest } from '../models/product-structure-api.models';
import type { ProductTreeResponseDto } from '../models/product-structure-api.models';
import type { ProductTreeNodeDto } from '../models/product-structure-api.models';
import type { ProductDetailApiResponse } from '../models/product-structure-api.models';
import type { ProductSearchCondition } from '../models/product-structure-view.models';
import type { ProductTreeNode } from '../models/product-structure-view.models';
import type { ProductDetail } from '../models/product-structure-view.models';
import type { NodeSelection } from '../models/product-structure-view.models';
import type { PendingOperation } from '../models/product-structure-view.models';
import type { PendingOperationType } from '../models/product-structure-view.models';
import type { SearchTreePayload } from '../models/product-structure-payload.models';
import type { LoadTreePayload } from '../models/product-structure-payload.models';
import type { LoadTreeSuccessPayload } from '../models/product-structure-payload.models';
import type { SelectNodePayload } from '../models/product-structure-payload.models';
import type { LoadDetailPayload } from '../models/product-structure-payload.models';
import type { LoadDetailSuccessPayload } from '../models/product-structure-payload.models';
import type { SaveProductPayload } from '../models/product-structure-payload.models';
import type { SaveProductSuccessPayload } from '../models/product-structure-payload.models';
import type { ReloadTreeAfterSavePayload } from '../models/product-structure-payload.models';
import type { ReloadDetailPayload } from '../models/product-structure-payload.models';
import type { SetPendingOperationPayload } from '../models/product-structure-payload.models';
import type { ApiErrorPayload } from '../models/product-structure-payload.models';
import type { ApiError } from '../models/product-structure-common.models';
import type { FieldError } from '../models/product-structure-common.models';

export function mapSearchToApi(input: ProductSearchCondition): ProductStructureApiRequest {
  // TODO(spec): implement mapping "ツリー取得APIリクエスト生成"
  return input as unknown as ProductStructureApiRequest;
}

export function mapTreeDtoToView(input: ProductTreeNodeDto): ProductTreeNode {
  // TODO(spec): implement mapping "ツリーノードの画面用変換"
  return input as unknown as ProductTreeNode;
}

export function mapDetailApiToView(input: ProductDetailApiResponse): ProductDetail {
  // TODO(spec): implement mapping "詳細レスポンスの画面用変換"
  return input as unknown as ProductDetail;
}

export function mapSavePayloadToApi(input: SaveProductPayload): ProductUpdateApiRequest {
  // TODO(spec): implement mapping "更新APIリクエスト生成"
  return input as unknown as ProductUpdateApiRequest;
}

export function mapHttpError(error: unknown): ApiError {
  const message =
    typeof error === 'object' && error !== null && 'message' in error
      ? String((error as { message: unknown }).message)
      : 'Unexpected error';

  return {
    code: 'UNKNOWN',
    message,
    status: 0,
    fieldErrors: [],
  };
}
