// AUTO-GENERATED FILE.
// Source: specs/product-structure/
// Definition: specs/product-structure/resolved-screen.yaml
// Do not edit this file directly.

export interface ApiError {
  code: string;
  message: string;
  status: number;
  fieldErrors: FieldError[];
}

export interface FieldError {
  field: string;
  code: string;
  message: string;
}
