// AUTO-GENERATED FILE.
// Source: specs/product-structure/
// Definition: specs/product-structure/resolved-screen.yaml
// Do not edit this file directly.
import type { ProductStructureState } from '../store/product-structure.state';

export type ProductStructureViewModel = Pick<
  ProductStructureState,
  | 'searchCondition'
  | 'treeNodes'
  | 'selectedComponentId'
  | 'selectedProductId'
  | 'detail'
  | 'treeLoading'
  | 'detailLoading'
  | 'saving'
  | 'treeError'
  | 'detailError'
  | 'saveError'
  | 'concurrentUpdate'
  | 'pendingOperation'
  | 'reselectTarget'
>;
