// AUTO-GENERATED FILE.
// Source: specs/product-structure/
// Definition: specs/product-structure/resolved-screen.yaml
// Do not edit this file directly.

export interface ProductStructureApiRequest {
  keyword?: string;
  categoryId?: string | null;
}

export interface ProductDetailApiRequest {
  productId: string;
}

export interface ProductUpdateApiRequest {
  productId: string;
  productName: string;
  price: number;
  description: string;
  revision: number;
}

export interface ProductTreeResponseDto {
  nodes: ProductTreeNodeDto[];
}

export interface ProductTreeNodeDto {
  componentId: string;
  productId: string;
  productName: string;
  productCode: string;
  parentComponentId: string;
  children: ProductTreeNodeDto[];
}

export interface ProductDetailApiResponse {
  productId: string;
  productName: string;
  productCode: string;
  price: number;
  description: string;
  revision: number;
}
