// AUTO-GENERATED FILE.
// Source: specs/product-structure/
// Definition: specs/product-structure/resolved-screen.yaml
// Do not edit this file directly.
import type { ProductSearchCondition } from './product-structure-view.models';
import type { ProductTreeNode } from './product-structure-view.models';
import type { ProductDetail } from './product-structure-view.models';
import type { NodeSelection } from './product-structure-view.models';
import type { PendingOperation } from './product-structure-view.models';
import type { PendingOperationType } from './product-structure-view.models';
import type { ApiError } from './product-structure-common.models';
import type { FieldError } from './product-structure-common.models';

export interface SearchTreePayload {
  condition: ProductSearchCondition;
}

export interface LoadTreePayload {
  condition: ProductSearchCondition;
}

export interface LoadTreeSuccessPayload {
  nodes: ProductTreeNode[];
}

export interface SelectNodePayload {
  selection: NodeSelection;
}

export interface LoadDetailPayload {
  productId: string;
}

export interface LoadDetailSuccessPayload {
  detail: ProductDetail;
}

export interface SaveProductPayload {
  componentId: string;
  productId: string;
  productName: string;
  price: number;
  description: string;
  revision: number;
}

export interface SaveProductSuccessPayload {
  componentId: string;
  detail: ProductDetail;
}

export interface ReloadTreeAfterSavePayload {
  condition: ProductSearchCondition;
  selection: NodeSelection;
}

export interface ReloadDetailPayload {
  productId: string;
}

export interface SetPendingOperationPayload {
  pending: PendingOperation;
}

export interface ApiErrorPayload {
  error: ApiError;
}
