// AUTO-GENERATED FILE.
// Source: specs/product-structure/
// Definition: specs/product-structure/resolved-screen.yaml
// Do not edit this file directly.
import type { ApiError } from './product-structure-common.models';
import type { FieldError } from './product-structure-common.models';

export interface ProductSearchCondition {
  keyword: string;
  categoryId: string | null;
}

export interface ProductTreeNode {
  componentId: string;
  productId: string;
  productName: string;
  productCode: string;
  parentComponentId: string;
  children: ProductTreeNode[];
}

export interface ProductDetail {
  productId: string;
  productName: string;
  productCode: string;
  price: number;
  description: string;
  revision: number;
}

export interface NodeSelection {
  componentId: string;
  productId: string;
}

export interface PendingOperation {
  operationType: PendingOperationType;
  selection: NodeSelection;
  searchCondition: ProductSearchCondition;
}

export interface PendingOperationType {
  value: string | string | string | string | string;
}
