// AUTO-GENERATED FILE.
// Source: specs/product-structure.md
// Definition: screens/product-structure.yaml
// Do not edit this file directly.
import { HttpErrorResponse } from '@angular/common/http';

import type {
  ProductDetailApiResponse,
  ProductTreeNodeDto,
  ProductStructureApiRequest,
  ProductTreeResponseDto,
  ProductUpdateApiRequest,
} from '../models/api';
import type { LoadTreePayload, SaveProductPayload } from '../models/actions';
import type { ApiError, ProductDetail, ProductTreeNode } from '../models/store';

/**
 * Pure mapping functions between API DTOs and view/store models. All request/
 * response transformation lives here so it is not scattered across the
 * Component, Reducer, or Service.
 */

export function mapTreeNode(dto: ProductTreeNodeDto): ProductTreeNode {
  return {
    productId: dto.productId,
    productName: dto.productName,
    productCode: dto.productCode,
    parentId: dto.parentId,
    children: (dto.children ?? []).map(mapTreeNode),
  };
}

export function mapTreeResponse(response: ProductTreeResponseDto): ProductTreeNode[] {
  return (response.nodes ?? []).map(mapTreeNode);
}

export function mapDetail(response: ProductDetailApiResponse): ProductDetail {
  return {
    productId: response.productId,
    productName: response.productName,
    productCode: response.productCode,
    price: response.price,
    description: response.description,
    revision: response.revision,
  };
}

export function toTreeRequest(payload: LoadTreePayload): ProductStructureApiRequest {
  return {
    keyword: payload.keyword,
    categoryId: payload.categoryId,
  };
}

export function toUpdateRequest(payload: SaveProductPayload): ProductUpdateApiRequest {
  return {
    productName: payload.productName,
    price: payload.price,
    description: payload.description,
    revision: payload.revision,
  };
}

export function toApiError(error: unknown): ApiError {
  if (error instanceof HttpErrorResponse) {
    const body = error.error as { code?: string; message?: string } | null;
    return {
      code: body && body.code ? body.code : String(error.status),
      message: body && body.message ? body.message : error.message,
    };
  }
  if (error instanceof Error) {
    return { code: 'UNKNOWN', message: error.message };
  }
  return { code: 'UNKNOWN', message: 'Unexpected error' };
}
