// AUTO-GENERATED FILE.
// Source: specs/product-structure/
// Definition: specs/product-structure/resolved-screen.yaml
// Do not edit this file directly.
import { ChangeDetectionStrategy, Component, OnInit, inject } from '@angular/core';
import { Store } from '@ngrx/store';

import { ProductStructureActions } from '../../store/product-structure.actions';
import { selectProductStructureViewModel } from '../../store/product-structure.selectors';
import type { ReloadDetailPayload } from '../../models/product-structure-payload.models';
import type { SaveProductPayload } from '../../models/product-structure-payload.models';
import type { NodeSelection } from '../../models/product-structure-view.models';
import type { ProductSearchCondition } from '../../models/product-structure-view.models';

@Component({
  selector: 'app-product-structure-page',
  standalone: false,
  templateUrl: './product-structure-page.component.html',
  styleUrl: './product-structure-page.component.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ProductStructurePageComponent implements OnInit {
  private readonly store = inject(Store);

  readonly vm$ = this.store.select(selectProductStructureViewModel);

  ngOnInit(): void {
    this.store.dispatch(ProductStructureActions.enterPage());
  }

  onSearchRequested(payload: ProductSearchCondition): void {
    this.store.dispatch(ProductStructureActions.searchTree({ condition: payload }));
  }

  onClearRequested(): void {
    this.store.dispatch(ProductStructureActions.clearSearch());
  }

  onNodeSelected(payload: NodeSelection): void {
    this.store.dispatch(ProductStructureActions.selectNode({ selection: payload }));
  }

  onNodeToggled(payload: string): void {}

  onSaveRequested(payload: SaveProductPayload): void {
    this.store.dispatch(ProductStructureActions.saveProduct(payload));
  }

  onCancelRequested(): void {
    this.store.dispatch(ProductStructureActions.cancelEdit());
  }

  onReloadRequested(payload: ReloadDetailPayload): void {
    this.store.dispatch(ProductStructureActions.reloadDetail(payload));
  }

  onDirtyChanged(payload: boolean): void {}

  onConfirmed(): void {
    this.store.dispatch(ProductStructureActions.confirmDiscardChanges());
  }

  onCancelled(): void {
    this.store.dispatch(ProductStructureActions.cancelDiscardChanges());
  }
}
