// AUTO-GENERATED FILE.
// Source: specs/product-structure.md
// Definition: screens/product-structure.yaml
// Do not edit this file directly.
import type { ApiError } from '../store/api-error.model';
import type { PendingOperation } from '../store/pending-operation.model';
import type { ProductDetail } from '../store/product-detail.model';
import type { ProductTreeNode } from '../store/product-tree-node.model';

/** Action payload model. May include UI-only fields (e.g. componentId). */
export interface LoadTreePayload {
  /** 検索キーワード */
  keyword: string;
  /** カテゴリID */
  categoryId: string | null;
}

/** Action payload model. May include UI-only fields (e.g. componentId). */
export interface LoadTreeSuccessPayload {
  /** 取得したツリー */
  nodes: ProductTreeNode[];
}

/** Action payload model. May include UI-only fields (e.g. componentId). */
export interface SelectNodePayload {
  /** 選択した製品ID */
  productId: string;
}

/** Action payload model. May include UI-only fields (e.g. componentId). */
export interface LoadDetailPayload {
  /** 取得する製品ID */
  productId: string;
}

/** Action payload model. May include UI-only fields (e.g. componentId). */
export interface LoadDetailSuccessPayload {
  /** 取得した製品詳細 */
  detail: ProductDetail;
}

/** Action payload model. May include UI-only fields (e.g. componentId). */
export interface SaveProductPayload {
  /** 製品ID */
  productId: string;
  /** 製品名 */
  productName: string;
  /** 価格 */
  price: number;
  /** 説明 */
  description: string | null;
  /** リビジョン */
  revision: number;
}

/** Action payload model. May include UI-only fields (e.g. componentId). */
export interface SaveProductSuccessPayload {
  /** 保存後の製品詳細 */
  detail: ProductDetail;
}

/** Action payload model. May include UI-only fields (e.g. componentId). */
export interface ReloadDetailPayload {
  /** 再取得する製品ID */
  productId: string;
}

/** Action payload model. May include UI-only fields (e.g. componentId). */
export interface LoadPermissionsSuccessPayload {
  /** 取得した権限コード */
  permissions: string[];
}

/** Action payload model. May include UI-only fields (e.g. componentId). */
export interface SetPendingOperationPayload {
  /** 保留操作 */
  pending: PendingOperation;
}

/** Action payload model. May include UI-only fields (e.g. componentId). */
export interface ApiErrorPayload {
  /** APIエラー */
  error: ApiError;
}
